### ISSUE TITLE
about  project  for   what  

### ISSUE THREAD

**Issue by zhanghongyong123456** [vgthengane/pix2pixHD#1]
I want to know what the purpose of this project is, isn't it?
https://github.com/bcmi/Object-Shadow-Generation-Dataset-DESOBA  and 
![image](https://user-images.githubusercontent.com/48466610/145952208-b70caf3e-dfcb-4adb-8af8-26955721153c.png)

**Comment by vgthengane** [comment]
I am not sure, If I understood you. Can you elaborate? Is it relevant to this repository?
